create table
  public.potion_inventory (
    id bigint generated by default as identity,
    r integer null,
    g integer null,
    b integer null,
    d integer null,
    num integer null,
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_green_ml integer null default 0,
    gold integer null default 100,
    num_red_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.days (
    id bigint generated by default as identity,
    day text null default '""'::text,
    hour bigint null default '0'::bigint,
    constraint days_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.customers_info (
    id bigint generated by default as identity,
    name text null default '""'::text,
    class text null default '""'::text,
    level smallint null default '0'::smallint,
    cart_id smallint null default '0'::smallint,
    day text null,
    hour integer null default 0,
    visit_id integer null default 0,
    constraint customers_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.catalog (
    id bigint generated by default as identity,
    sku text null default '""'::text,
    name text null default '""'::text,
    price integer null default 0,
    potion_id text null,
    constraint catalog_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    customer_name text null default '""'::text,
    cart_id integer generated by default as identity,
    constraint carts_pkey primary key (id, cart_id),
    constraint carts_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    cart_id integer null default 0,
    sku text null default '""'::text,
    quantity integer null default 0,
    constraint cart_items_pkey primary key (id)
  ) tablespace pg_default;